/* ==========================================================================
   FASE 2: ACADÉMICO Y CURRICULAR (CORREGIDO V2)
   
   Correcciones:
   1. LIMPIEZA DE FASE 2: Elimina datos específicos de esta fase (IDs > X) 
      para permitir re-ejecución limpia sin duplicados.
   2. TRUNCAMIENTO: Se acortaron los CODIGO_COHORTE a máx 10 caracteres 
      (ej: 'MALLA-SOFT-2022' -> 'M-SOFT-22').
   ========================================================================== */

USE fmerino_GestionUniversitaria;
GO

SET NOCOUNT ON;
PRINT '>>> INICIANDO FASE 2 (V2 - CON LIMPIEZA Y CORRECCIONES)...';

/* ==========================================================================
   SECCIÓN 0: LIMPIEZA PREVIA DE FASE 2 (RESET PARCIAL)
   Borramos solo los datos que esta fase pretende crear para evitar choques.
   ========================================================================== */
PRINT '0. Limpiando datos previos de Fase 2 (si existen)...';

-- Borrar tablas de relación pura creadas en esta fase
DELETE FROM TIENE_PRERREQUISITO;
DELETE FROM CORREQUISITO;
DELETE FROM DETALLE_MALLA;

-- Borrar Mallas (Padres de detalle)
DELETE FROM MALLA_CURRICULAR;

-- Borrar Títulos (Hijos de Docente)
DELETE FROM TITULO_ACADEMICO;

-- Borrar Estudiantes del Lote 2 (IDs > 125)
DELETE FROM ESTUDIANTE WHERE ID_ESTUDIANTE > 125;

-- Borrar Asignaturas de Fase 2 (IDs > 50)
DELETE FROM ASIGNATURA WHERE ID_ASIGNATURA > 50;

-- Borrar Carreras de Fase 2 (IDs > 8)
-- Nota: Primero borramos carreras para liberar a los docentes coordinadores
DELETE FROM CARRERA WHERE ID_CARRERA > 8;

-- Borrar Docentes de Fase 2 (IDs > 25)
DELETE FROM DOCENTE WHERE ID_DOCENTE > 25;

PRINT '   > Limpieza completada. Insertando datos limpios...';


/* ==========================================================================
   SECCIÓN DE INSERCIÓN
   ========================================================================== */

/* --------------------------------------------------------------------------
   9. COMPLETAR DOCENTES (75 Registros Adicionales -> Total 100)
   IDs: 26 al 100
   -------------------------------------------------------------------------- */
PRINT '9. Insertando resto de Docentes (75 registros)...';

INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) VALUES (26, 1, 'DOC026', '1700000026', 'Marcelo', 'Ebrard', 'marcelo.ebrard@epn.edu.ec', 'TIEMPO_COMPLETO', 'AGREGADO', '2019-02-01');
INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) VALUES (27, 2, 'DOC027', '1700000027', 'Claudia', 'Shein', 'claudia.shein@epn.edu.ec', 'TIEMPO_COMPLETO', 'TITULAR', '2015-06-15');
INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) VALUES (28, 3, 'DOC028', '1700000028', 'Xochitl', 'Galvez', 'xochitl.galvez@epn.edu.ec', 'MEDIO_TIEMPO', 'AUXILIAR', '2021-03-10');
INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) VALUES (29, 4, 'DOC029', '1700000029', 'Samuel', 'Garcia', 'samuel.garcia@epn.edu.ec', 'TIEMPO_COMPLETO', 'AGREGADO', '2018-09-20');
INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) VALUES (30, 5, 'DOC030', '1700000030', 'Luis', 'Colosio', 'luis.colosio@epn.edu.ec', 'TIEMPO_COMPLETO', 'TITULAR', '2010-01-01');

-- Generación rápida de docentes genéricos (31-100)
DECLARE @i INT = 31;
WHILE @i <= 100
BEGIN
    INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO)
    VALUES (
        @i, 
        (@i % 8) + 1, 
        'DOC' + RIGHT('000' + CAST(@i AS VARCHAR), 3),
        '1700000' + CAST(@i AS VARCHAR),
        'DocenteNombre' + CAST(@i AS VARCHAR),
        'DocenteApellido' + CAST(@i AS VARCHAR),
        'docente.' + CAST(@i AS VARCHAR) + '@epn.edu.ec',
        CASE WHEN @i % 3 = 0 THEN 'MEDIO_TIEMPO' ELSE 'TIEMPO_COMPLETO' END,
        CASE WHEN @i % 4 = 0 THEN 'AUXILIAR' WHEN @i % 4 = 1 THEN 'AGREGADO' ELSE 'TITULAR' END,
        DATEADD(day, -@i*10, '2023-01-01')
    );
    SET @i = @i + 1;
END

/* --------------------------------------------------------------------------
   10. TÍTULOS ACADÉMICOS
   -------------------------------------------------------------------------- */
PRINT '10. Insertando Títulos Académicos de Docentes...';
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (1, 1, 'PhD en Ciencias de la Computación', 'DOCTORADO', 'MIT');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (2, 2, 'PhD en Administración de Empresas', 'DOCTORADO', 'Harvard');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (3, 3, 'PhD en Ingeniería Estructural', 'DOCTORADO', 'Stanford');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (4, 4, 'PhD en Sistemas Eléctricos', 'DOCTORADO', 'CalTech');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (5, 5, 'PhD en Termodinámica', 'DOCTORADO', 'TUM Germany');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (6, 6, 'PhD en Procesos Químicos', 'DOCTORADO', 'UNAM');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (7, 7, 'PhD en Matemáticas Puras', 'DOCTORADO', 'Oxford');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (8, 8, 'PhD en Geofísica', 'DOCTORADO', 'U. Tokyo');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (9, 9, 'MSc en Ingeniería de Software', 'MAESTRIA', 'EPN');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (10, 10, 'MBA', 'MAESTRIA', 'INCAE');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (11, 11, 'MSc en Hidráulica', 'MAESTRIA', 'UNAM');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (12, 12, 'MSc en Automatización', 'MAESTRIA', 'Politécnica Madrid');

/* --------------------------------------------------------------------------
   11. COMPLETAR CARRERAS (Total 30)
   -------------------------------------------------------------------------- */
PRINT '11. Insertando resto de Carreras...';

-- Posgrados
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (9, 1, 26, 'Maestría en Ciberseguridad', 'POSGRADO', 'ONLINE', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (10, 1, 27, 'Maestría en Ciencia de Datos', 'POSGRADO', 'SEMIPRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (11, 2, 28, 'MBA Ejecutivo', 'POSGRADO', 'ONLINE', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (12, 3, 29, 'Maestría en Vías Terrestres', 'POSGRADO', 'PRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (13, 4, 30, 'Maestría en Energías Renovables', 'POSGRADO', 'SEMIPRESENCIAL', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (14, 5, 31, 'Maestría en Diseño Automotriz', 'POSGRADO', 'PRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (15, 6, 32, 'Maestría en Procesos Industriales', 'POSGRADO', 'PRESENCIAL', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (16, 7, 33, 'Doctorado en Matemática Aplicada', 'POSGRADO', 'PRESENCIAL', 8);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (17, 8, 34, 'Maestría en Hidrocarburos', 'POSGRADO', 'SEMIPRESENCIAL', 3);

-- Tecnologías y otras Carreras de Grado
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (18, 1, 35, 'Tecnología en Desarrollo Web', 'TECNOLOGICO', 'ONLINE', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (19, 1, 36, 'Tecnología en Redes y Telecom', 'TECNOLOGICO', 'PRESENCIAL', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (20, 2, 37, 'Tecnología en Marketing Digital', 'TECNOLOGICO', 'ONLINE', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (21, 3, 38, 'Ingeniería Ambiental', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (22, 4, 39, 'Ingeniería en Telecomunicaciones', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (23, 5, 40, 'Ingeniería Mecatrónica', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (24, 6, 41, 'Ingeniería en Alimentos', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (25, 7, 42, 'Física Nuclear', 'GRADO', 'PRESENCIAL', 10);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (26, 8, 43, 'Ingeniería Geológica', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (27, 2, 44, 'Economía', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (28, 1, 45, 'Ingeniería en Computación', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (29, 3, 46, 'Arquitectura', 'GRADO', 'PRESENCIAL', 10);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (30, 4, 47, 'Ingeniería en Control', 'GRADO', 'PRESENCIAL', 9);

/* --------------------------------------------------------------------------
   12. ASIGNATURAS AVANZADAS
   -------------------------------------------------------------------------- */
PRINT '12. Insertando 150 Asignaturas Avanzadas...';

-- Bloque Software Avanzado
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (51, 'SW301', 'Inteligencia Artificial', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (52, 'SW302', 'Machine Learning', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (53, 'SW303', 'Deep Learning', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (54, 'SW304', 'Sistemas Operativos', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (55, 'SW305', 'Redes de Computadoras I', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (56, 'SW306', 'Redes de Computadoras II', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (57, 'SW307', 'Seguridad Informática', 3, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (58, 'SW308', 'Desarrollo Web Fullstack', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (59, 'SW309', 'Desarrollo Móvil', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (60, 'SW310', 'Cloud Computing', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (61, 'SW400', 'Tesis I', 5, 'OBLIGATORIA', 'Investigación');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (62, 'SW401', 'Tesis II', 5, 'OBLIGATORIA', 'Investigación');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (63, 'SW311', 'DevOps', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (64, 'SW312', 'QA y Testing', 3, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (65, 'SW313', 'Arquitectura de Microservicios', 3, 'OPTATIVA', 'Software');

-- Generación de Asignaturas Genéricas
DECLARE @j INT = 66;
WHILE @j <= 200
BEGIN
    INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO)
    VALUES (
        @j,
        'GEN' + CAST(@j AS VARCHAR),
        CASE 
            WHEN @j % 5 = 0 THEN 'Gestión de Proyectos ' + CAST(@j AS VARCHAR)
            WHEN @j % 5 = 1 THEN 'Matemática Avanzada ' + CAST(@j AS VARCHAR)
            WHEN @j % 5 = 2 THEN 'Física Aplicada ' + CAST(@j AS VARCHAR)
            WHEN @j % 5 = 3 THEN 'Administración ' + CAST(@j AS VARCHAR)
            ELSE 'Tecnología Específica ' + CAST(@j AS VARCHAR)
        END,
        (@j % 3) + 2,
        CASE WHEN @j % 4 = 0 THEN 'OPTATIVA' ELSE 'OBLIGATORIA' END,
        'General'
    );
    SET @j = @j + 1;
END

/* --------------------------------------------------------------------------
   13. MALLAS CURRICULARES (Nombres cortos para evitar error 2628)
   -------------------------------------------------------------------------- */
PRINT '13. Creando Mallas Curriculares y Detalles...';

-- Malla 1: Ingeniería de Software
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (1, 1, 'M-SOFT-22', '2022-01-15', 240, 'VIGENTE');
-- Malla 2: Administración
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (2, 2, 'M-ADM-22', '2022-01-20', 220, 'VIGENTE');
-- Malla 3: Civil
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (3, 3, 'M-CIV-21', '2021-06-15', 250, 'VIGENTE');
-- Malla 4: Eléctrica
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (4, 4, 'M-ELE-20', '2020-09-01', 245, 'NO_VIGENTE');
-- Malla 5: Eléctrica Nueva
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (5, 4, 'M-ELE-24', '2024-01-10', 240, 'VIGENTE');

-- Detalle Malla Software (Malla 1)
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (1, 1, 1, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (2, 1, 1, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (10, 1, 1, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (11, 1, 1, 32, 64);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (3, 1, 2, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (21, 1, 2, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (22, 1, 3, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (23, 1, 3, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (24, 1, 4, 48, 16);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (54, 1, 4, 48, 32);

/* --------------------------------------------------------------------------
   14. PRERREQUISITOS Y CORREQUISITOS
   -------------------------------------------------------------------------- */
PRINT '14. Estableciendo Prerrequisitos y Correquisitos...';

INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (1, 2);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (2, 3);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (3, 4);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (3, 5);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (10, 11);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (11, 21);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (11, 22);
INSERT INTO CORREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (6, 2);

/* --------------------------------------------------------------------------
   15. ESTUDIANTES LOTE 2 (125 Registros -> Total 250)
   -------------------------------------------------------------------------- */
PRINT '15. Insertando Estudiantes Lote 2 (125 registros)...';

DECLARE @k INT = 126;
WHILE @k <= 250
BEGIN
    INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, NUMERO_UNICO, CEDULA, NOMBRES_ESTUDIANTE, APELLIDOS_ESTUDIANTE, EMAIL_INSTITUCIONAL, FECHA_INGRESO, ESTADO_ESTUDIANTE, IRA)
    VALUES (
        @k,
        'EST' + CAST(@k AS VARCHAR),
        '172000' + RIGHT('0000' + CAST(@k AS VARCHAR), 4),
        'Estudiante' + CAST(@k AS VARCHAR),
        'Apellido' + CAST(@k AS VARCHAR),
        'estudiante.' + CAST(@k AS VARCHAR) + '@epn.edu.ec',
        CASE WHEN @k % 2 = 0 THEN '2023-04-01' ELSE '2024-04-01' END,
        CASE WHEN @k % 10 = 0 THEN 'SUSPENDIDO' ELSE 'ACTIVO' END,
        7.0 + (@k % 30) / 10.0 
    );
    SET @k = @k + 1;
END

PRINT '>>> FASE 2 COMPLETADA CON ÉXITO.';
GO