/*==============================================================*/
/* DBMS name:      Microsoft SQL Server 2008                    */
/* Created on:     1/2/2026 3:55:56 PM                          */
/*==============================================================*/


IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('ASIGNACION_BECA') AND O.NAME = 'FK_ASIGNACI_ES_TIPO_B_TIPO_BEC')
ALTER TABLE ASIGNACION_BECA
   DROP CONSTRAINT FK_ASIGNACI_ES_TIPO_B_TIPO_BEC
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('ASIGNACION_BECA') AND O.NAME = 'FK_ASIGNACI_RECIBE_BE_ESTUDIAN')
ALTER TABLE ASIGNACION_BECA
   DROP CONSTRAINT FK_ASIGNACI_RECIBE_BE_ESTUDIAN
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('AUTORIA') AND O.NAME = 'FK_AUTORIA_ESCRIBE_A_DOCENTE')
ALTER TABLE AUTORIA
   DROP CONSTRAINT FK_AUTORIA_ESCRIBE_A_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('AUTORIA') AND O.NAME = 'FK_AUTORIA_TIENE_AUT_PUBLICAC')
ALTER TABLE AUTORIA
   DROP CONSTRAINT FK_AUTORIA_TIENE_AUT_PUBLICAC
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CALIFICACION') AND O.NAME = 'FK_CALIFICA_GENERA_CA_OFERTA_A')
ALTER TABLE CALIFICACION
   DROP CONSTRAINT FK_CALIFICA_GENERA_CA_OFERTA_A
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CALIFICACION') AND O.NAME = 'FK_CALIFICA_TIENE_DET_MATRICUL')
ALTER TABLE CALIFICACION
   DROP CONSTRAINT FK_CALIFICA_TIENE_DET_MATRICUL
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CARRERA') AND O.NAME = 'FK_CARRERA_ADMINISTR_FACULTAD')
ALTER TABLE CARRERA
   DROP CONSTRAINT FK_CARRERA_ADMINISTR_FACULTAD
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CARRERA') AND O.NAME = 'FK_CARRERA_TIENE_COO_DOCENTE')
ALTER TABLE CARRERA
   DROP CONSTRAINT FK_CARRERA_TIENE_COO_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('COLABORAN_EN') AND O.NAME = 'FK_COLABORA_COLABORAN_DOCENTE')
ALTER TABLE COLABORAN_EN
   DROP CONSTRAINT FK_COLABORA_COLABORAN_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('COLABORAN_EN') AND O.NAME = 'FK_COLABORA_COLABORAN_PROYECTO')
ALTER TABLE COLABORAN_EN
   DROP CONSTRAINT FK_COLABORA_COLABORAN_PROYECTO
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CORREQUISITO') AND O.NAME = 'FK_CORREQ_ASIG_A')
ALTER TABLE CORREQUISITO
   DROP CONSTRAINT FK_CORREQ_ASIG_A
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('CORREQUISITO') AND O.NAME = 'FK_CORREQ_ASIG_B')
ALTER TABLE CORREQUISITO
   DROP CONSTRAINT FK_CORREQ_ASIG_B
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DEPARTAMENTO') AND O.NAME = 'FK_DEPARTAM_TIENE_DEP_FACULTAD')
ALTER TABLE DEPARTAMENTO
   DROP CONSTRAINT FK_DEPARTAM_TIENE_DEP_FACULTAD
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DETALLE_MALLA') AND O.NAME = 'FK_DETALLE__ES_PARTE__MALLA_CU')
ALTER TABLE DETALLE_MALLA
   DROP CONSTRAINT FK_DETALLE__ES_PARTE__MALLA_CU
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DETALLE_MALLA') AND O.NAME = 'FK_DETALLE__SE_PRESEN_ASIGNATU')
ALTER TABLE DETALLE_MALLA
   DROP CONSTRAINT FK_DETALLE__SE_PRESEN_ASIGNATU
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DOCENTE') AND O.NAME = 'FK_DOCENTE_ENSENIAN__FACULTAD')
ALTER TABLE DOCENTE
   DROP CONSTRAINT FK_DOCENTE_ENSENIAN__FACULTAD
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DOCENTE') AND O.NAME = 'FK_DOCENTE_TIENE_COO_CARRERA')
ALTER TABLE DOCENTE
   DROP CONSTRAINT FK_DOCENTE_TIENE_COO_CARRERA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('DOCENTE') AND O.NAME = 'FK_DOCENTE_TIENE_DEC_FACULTAD')
ALTER TABLE DOCENTE
   DROP CONSTRAINT FK_DOCENTE_TIENE_DEC_FACULTAD
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('FACULTAD') AND O.NAME = 'FK_FACULTAD_TIENE_DEC_DOCENTE')
ALTER TABLE FACULTAD
   DROP CONSTRAINT FK_FACULTAD_TIENE_DEC_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('HISTORIAL_ACADEMICO') AND O.NAME = 'FK_HISTORIA_OBTUVO_RE_PERIODO_')
ALTER TABLE HISTORIAL_ACADEMICO
   DROP CONSTRAINT FK_HISTORIA_OBTUVO_RE_PERIODO_
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('HISTORIAL_ACADEMICO') AND O.NAME = 'FK_HISTORIA_TIENE_HIS_ESTUDIAN')
ALTER TABLE HISTORIAL_ACADEMICO
   DROP CONSTRAINT FK_HISTORIA_TIENE_HIS_ESTUDIAN
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('HORARIO_CLASE') AND O.NAME = 'FK_HORARIO__SE_DICTA__OFERTA_A')
ALTER TABLE HORARIO_CLASE
   DROP CONSTRAINT FK_HORARIO__SE_DICTA__OFERTA_A
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('HORARIO_CLASE') AND O.NAME = 'FK_HORARIO__TIENE_HOR_AULA')
ALTER TABLE HORARIO_CLASE
   DROP CONSTRAINT FK_HORARIO__TIENE_HOR_AULA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('MALLA_CURRICULAR') AND O.NAME = 'FK_MALLA_CU_TIENE_CAR_CARRERA')
ALTER TABLE MALLA_CURRICULAR
   DROP CONSTRAINT FK_MALLA_CU_TIENE_CAR_CARRERA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('MATRICULA') AND O.NAME = 'FK_MATRICUL_HA_REALIZ_ESTUDIAN')
ALTER TABLE MATRICULA
   DROP CONSTRAINT FK_MATRICUL_HA_REALIZ_ESTUDIAN
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('MATRICULA') AND O.NAME = 'FK_MATRICUL_SE_REALIZ_PERIODO_')
ALTER TABLE MATRICULA
   DROP CONSTRAINT FK_MATRICUL_SE_REALIZ_PERIODO_
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('OFERTA_ASIGNATURA') AND O.NAME = 'FK_OFERTA_A_DESIGNADO_DOCENTE')
ALTER TABLE OFERTA_ASIGNATURA
   DROP CONSTRAINT FK_OFERTA_A_DESIGNADO_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('OFERTA_ASIGNATURA') AND O.NAME = 'FK_OFERTA_A_TIENE_ASI_ASIGNATU')
ALTER TABLE OFERTA_ASIGNATURA
   DROP CONSTRAINT FK_OFERTA_A_TIENE_ASI_ASIGNATU
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('OFERTA_ASIGNATURA') AND O.NAME = 'FK_OFERTA_A_TIENE_PER_PERIODO_')
ALTER TABLE OFERTA_ASIGNATURA
   DROP CONSTRAINT FK_OFERTA_A_TIENE_PER_PERIODO_
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PRESTAMO') AND O.NAME = 'FK_PRESTAMO_ES_PRESTA_LIBRO')
ALTER TABLE PRESTAMO
   DROP CONSTRAINT FK_PRESTAMO_ES_PRESTA_LIBRO
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PRESTAMO') AND O.NAME = 'FK_PRESTAMO_SOLICITA__ESTUDIAN')
ALTER TABLE PRESTAMO
   DROP CONSTRAINT FK_PRESTAMO_SOLICITA__ESTUDIAN
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PROCESO_TITULACION') AND O.NAME = 'FK_PROCESO__SOLICITA__ESTUDIAN')
ALTER TABLE PROCESO_TITULACION
   DROP CONSTRAINT FK_PROCESO__SOLICITA__ESTUDIAN
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PROCESO_TITULACION') AND O.NAME = 'FK_PROCESO__TUTORA_PR_DOCENTE')
ALTER TABLE PROCESO_TITULACION
   DROP CONSTRAINT FK_PROCESO__TUTORA_PR_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PROYECTO_INVESTIGACION') AND O.NAME = 'FK_PROYECTO_DIRIGE_PR_DOCENTE')
ALTER TABLE PROYECTO_INVESTIGACION
   DROP CONSTRAINT FK_PROYECTO_DIRIGE_PR_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PROYECTO_INVESTIGACION') AND O.NAME = 'FK_PROYECTO_GESTIONA__DEPARTAM')
ALTER TABLE PROYECTO_INVESTIGACION
   DROP CONSTRAINT FK_PROYECTO_GESTIONA__DEPARTAM
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('PUBLICACION') AND O.NAME = 'FK_PUBLICAC_PRODUCE_P_PROYECTO')
ALTER TABLE PUBLICACION
   DROP CONSTRAINT FK_PUBLICAC_PRODUCE_P_PROYECTO
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TIENE_PRERREQUISITO') AND O.NAME = 'FK_PRERREQ_ASIG_HIJA')
ALTER TABLE TIENE_PRERREQUISITO
   DROP CONSTRAINT FK_PRERREQ_ASIG_HIJA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TIENE_PRERREQUISITO') AND O.NAME = 'FK_PRERREQ_ASIG_PADRE')
ALTER TABLE TIENE_PRERREQUISITO
   DROP CONSTRAINT FK_PRERREQ_ASIG_PADRE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TITULO_ACADEMICO') AND O.NAME = 'FK_TITULO_A_POSEE_TIT_DOCENTE')
ALTER TABLE TITULO_ACADEMICO
   DROP CONSTRAINT FK_TITULO_A_POSEE_TIT_DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TRIBUNAL_GRADO') AND O.NAME = 'FK_TRIBUNAL_TRIBUNAL__DOCENTE')
ALTER TABLE TRIBUNAL_GRADO
   DROP CONSTRAINT FK_TRIBUNAL_TRIBUNAL__DOCENTE
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TRIBUNAL_GRADO') AND O.NAME = 'FK_TRIBUNAL_TRIBUNAL__PROCESO_')
ALTER TABLE TRIBUNAL_GRADO
   DROP CONSTRAINT FK_TRIBUNAL_TRIBUNAL__PROCESO_
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('ASIGNACION_BECA')
            AND   NAME  = 'ES_TIPO_BECA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX ASIGNACION_BECA.ES_TIPO_BECA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('ASIGNACION_BECA')
            AND   NAME  = 'RECIBE_BECA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX ASIGNACION_BECA.RECIBE_BECA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('ASIGNACION_BECA')
            AND   TYPE = 'U')
   DROP TABLE ASIGNACION_BECA
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('ASIGNATURA')
            AND   TYPE = 'U')
   DROP TABLE ASIGNATURA
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('AULA')
            AND   TYPE = 'U')
   DROP TABLE AULA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('AUTORIA')
            AND   NAME  = 'TIENE_AUTORES_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX AUTORIA.TIENE_AUTORES_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('AUTORIA')
            AND   NAME  = 'ESCRIBE_ARTICULO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX AUTORIA.ESCRIBE_ARTICULO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('AUTORIA')
            AND   TYPE = 'U')
   DROP TABLE AUTORIA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CALIFICACION')
            AND   NAME  = 'GENERA_CALIFICACIONES_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CALIFICACION.GENERA_CALIFICACIONES_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CALIFICACION')
            AND   NAME  = 'TIENE_DETALLE_NOTAS_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CALIFICACION.TIENE_DETALLE_NOTAS_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('CALIFICACION')
            AND   TYPE = 'U')
   DROP TABLE CALIFICACION
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CARRERA')
            AND   NAME  = 'TIENE_COORDINADOR2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CARRERA.TIENE_COORDINADOR2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CARRERA')
            AND   NAME  = 'ADMINISTRA_CARRERA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CARRERA.ADMINISTRA_CARRERA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('CARRERA')
            AND   TYPE = 'U')
   DROP TABLE CARRERA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('COLABORAN_EN')
            AND   NAME  = 'COLABORAN_EN_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX COLABORAN_EN.COLABORAN_EN_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('COLABORAN_EN')
            AND   NAME  = 'COLABORAN_EN2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX COLABORAN_EN.COLABORAN_EN2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('COLABORAN_EN')
            AND   TYPE = 'U')
   DROP TABLE COLABORAN_EN
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CORREQUISITO')
            AND   NAME  = 'CORREQUISITO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CORREQUISITO.CORREQUISITO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('CORREQUISITO')
            AND   NAME  = 'CORREQUISITO2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX CORREQUISITO.CORREQUISITO2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('CORREQUISITO')
            AND   TYPE = 'U')
   DROP TABLE CORREQUISITO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DEPARTAMENTO')
            AND   NAME  = 'TIENE_DEPARTAMENTOS_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DEPARTAMENTO.TIENE_DEPARTAMENTOS_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DEPARTAMENTO')
            AND   TYPE = 'U')
   DROP TABLE DEPARTAMENTO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DETALLE_MALLA')
            AND   NAME  = 'SE_PRESENTA_EN_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DETALLE_MALLA.SE_PRESENTA_EN_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DETALLE_MALLA')
            AND   NAME  = 'ES_PARTE_DE_MALLA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DETALLE_MALLA.ES_PARTE_DE_MALLA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DETALLE_MALLA')
            AND   TYPE = 'U')
   DROP TABLE DETALLE_MALLA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DOCENTE')
            AND   NAME  = 'TIENE_COORDINADOR_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DOCENTE.TIENE_COORDINADOR_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DOCENTE')
            AND   NAME  = 'ENSENIAN_EN_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DOCENTE.ENSENIAN_EN_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DOCENTE')
            AND   NAME  = 'TIENE_DECANO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DOCENTE.TIENE_DECANO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('DOCENTE')
            AND   TYPE = 'U')
   DROP TABLE DOCENTE
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('ESTUDIANTE')
            AND   TYPE = 'U')
   DROP TABLE ESTUDIANTE
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('FACULTAD')
            AND   NAME  = 'TIENE_DECANO2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX FACULTAD.TIENE_DECANO2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('FACULTAD')
            AND   TYPE = 'U')
   DROP TABLE FACULTAD
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('HISTORIAL_ACADEMICO')
            AND   NAME  = 'OBTUVO_RESULTADOS_EN_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX HISTORIAL_ACADEMICO.OBTUVO_RESULTADOS_EN_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('HISTORIAL_ACADEMICO')
            AND   NAME  = 'TIENE_HISTORIALES_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX HISTORIAL_ACADEMICO.TIENE_HISTORIALES_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('HISTORIAL_ACADEMICO')
            AND   TYPE = 'U')
   DROP TABLE HISTORIAL_ACADEMICO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('HORARIO_CLASE')
            AND   NAME  = 'SE_DICTA_EN_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX HORARIO_CLASE.SE_DICTA_EN_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('HORARIO_CLASE')
            AND   NAME  = 'TIENE_HORARIO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX HORARIO_CLASE.TIENE_HORARIO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('HORARIO_CLASE')
            AND   TYPE = 'U')
   DROP TABLE HORARIO_CLASE
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('LIBRO')
            AND   TYPE = 'U')
   DROP TABLE LIBRO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('MALLA_CURRICULAR')
            AND   NAME  = 'TIENE_CARRERA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX MALLA_CURRICULAR.TIENE_CARRERA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('MALLA_CURRICULAR')
            AND   TYPE = 'U')
   DROP TABLE MALLA_CURRICULAR
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('MATRICULA')
            AND   NAME  = 'SE_REALIZAN_PERIODO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX MATRICULA.SE_REALIZAN_PERIODO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('MATRICULA')
            AND   NAME  = 'HA_REALIZADO_MATRICULA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX MATRICULA.HA_REALIZADO_MATRICULA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('MATRICULA')
            AND   TYPE = 'U')
   DROP TABLE MATRICULA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('OFERTA_ASIGNATURA')
            AND   NAME  = 'DESIGNADO_OFERTA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX OFERTA_ASIGNATURA.DESIGNADO_OFERTA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('OFERTA_ASIGNATURA')
            AND   NAME  = 'TIENE_ASIGNATURA_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX OFERTA_ASIGNATURA.TIENE_ASIGNATURA_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('OFERTA_ASIGNATURA')
            AND   NAME  = 'TIENE_PERIODO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX OFERTA_ASIGNATURA.TIENE_PERIODO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('OFERTA_ASIGNATURA')
            AND   TYPE = 'U')
   DROP TABLE OFERTA_ASIGNATURA
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('PERIODO_ACADEMICO')
            AND   TYPE = 'U')
   DROP TABLE PERIODO_ACADEMICO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PRESTAMO')
            AND   NAME  = 'ES_PRESTADO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PRESTAMO.ES_PRESTADO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PRESTAMO')
            AND   NAME  = 'SOLICITA_LIBRO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PRESTAMO.SOLICITA_LIBRO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('PRESTAMO')
            AND   TYPE = 'U')
   DROP TABLE PRESTAMO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PROCESO_TITULACION')
            AND   NAME  = 'TUTORA_PROCESO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PROCESO_TITULACION.TUTORA_PROCESO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PROCESO_TITULACION')
            AND   NAME  = 'SOLICITA_TITULACION_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PROCESO_TITULACION.SOLICITA_TITULACION_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('PROCESO_TITULACION')
            AND   TYPE = 'U')
   DROP TABLE PROCESO_TITULACION
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PROYECTO_INVESTIGACION')
            AND   NAME  = 'GESTIONA_INVESTIGACION_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PROYECTO_INVESTIGACION.GESTIONA_INVESTIGACION_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PROYECTO_INVESTIGACION')
            AND   NAME  = 'DIRIGE_PROYECTO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PROYECTO_INVESTIGACION.DIRIGE_PROYECTO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('PROYECTO_INVESTIGACION')
            AND   TYPE = 'U')
   DROP TABLE PROYECTO_INVESTIGACION
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('PUBLICACION')
            AND   NAME  = 'PRODUCE_PUBLICACION_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX PUBLICACION.PRODUCE_PUBLICACION_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('PUBLICACION')
            AND   TYPE = 'U')
   DROP TABLE PUBLICACION
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('TIENE_PRERREQUISITO')
            AND   NAME  = 'TIENE_PRERREQUISITO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX TIENE_PRERREQUISITO.TIENE_PRERREQUISITO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('TIENE_PRERREQUISITO')
            AND   NAME  = 'TIENE_PRERREQUISITO2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX TIENE_PRERREQUISITO.TIENE_PRERREQUISITO2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TIENE_PRERREQUISITO')
            AND   TYPE = 'U')
   DROP TABLE TIENE_PRERREQUISITO
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TIPO_BECA')
            AND   TYPE = 'U')
   DROP TABLE TIPO_BECA
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('TITULO_ACADEMICO')
            AND   NAME  = 'POSEE_TITULO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX TITULO_ACADEMICO.POSEE_TITULO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TITULO_ACADEMICO')
            AND   TYPE = 'U')
   DROP TABLE TITULO_ACADEMICO
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('TRIBUNAL_GRADO')
            AND   NAME  = 'TRIBUNAL_GRADO_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX TRIBUNAL_GRADO.TRIBUNAL_GRADO_FK
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('TRIBUNAL_GRADO')
            AND   NAME  = 'TRIBUNAL_GRADO2_FK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX TRIBUNAL_GRADO.TRIBUNAL_GRADO2_FK
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TRIBUNAL_GRADO')
            AND   TYPE = 'U')
   DROP TABLE TRIBUNAL_GRADO
go

/*==============================================================*/
/* Table: ASIGNACION_BECA                                       */
/*==============================================================*/
CREATE TABLE ASIGNACION_BECA (
   FECHA_ASIGNACION     DATETIME             NOT NULL,
   ID_ESTUDIANTE        INT                  NULL,
   ID_BECA              INT                  NULL,
   PORCENTAJE_COBERTURA NUMERIC(4,2)         NOT NULL,
   MONTO_ALIMENTACION   NUMERIC(6,2)         NULL,
   CONSTRAINT PK_ASIGNACION_BECA PRIMARY KEY NONCLUSTERED (FECHA_ASIGNACION)
)
go

/*==============================================================*/
/* Index: RECIBE_BECA_FK                                        */
/*==============================================================*/
CREATE INDEX RECIBE_BECA_FK ON ASIGNACION_BECA (
ID_ESTUDIANTE ASC
)
go

/*==============================================================*/
/* Index: ES_TIPO_BECA_FK                                       */
/*==============================================================*/
CREATE INDEX ES_TIPO_BECA_FK ON ASIGNACION_BECA (
ID_BECA ASC
)
go

/*==============================================================*/
/* Table: ASIGNATURA                                            */
/*==============================================================*/
CREATE TABLE ASIGNATURA (
   ID_ASIGNATURA        INT                  NOT NULL,
   CODIGO_ASIGNATURA    VARCHAR(15)          NOT NULL,
   NOMBRE_ASIGNATURA    VARCHAR(100)         NOT NULL,
   NUMERO_CREDITOS      INT                  NOT NULL,
   TIPO_ASIGNATURA      VARCHAR(50)          NOT NULL,
   AREA_CONOCIMIENTO    VARCHAR(50)          NOT NULL,
   CONSTRAINT PK_ASIGNATURA PRIMARY KEY NONCLUSTERED (ID_ASIGNATURA),
   CONSTRAINT UQ_ASIG_CODIGO UNIQUE (CODIGO_ASIGNATURA),
   CONSTRAINT CHK_TIPO_ASIGNATURA CHECK (TIPO_ASIGNATURA IN ('OBLIGATORIA', 'OPTATIVA', 'LIBRE_ELECCION'))
)
go

/*==============================================================*/
/* Table: AULA                                                  */
/*==============================================================*/
CREATE TABLE AULA (
   ID_AULA              INT                  NOT NULL,
   EDIFICIO_AULA        VARCHAR(10)          NOT NULL,
   PISO_AULA            INT                  NOT NULL,
   NUMERO_AULA          VARCHAR(10)          NOT NULL,
   CAPACIDAD_ESTUDIANTES INT                  NOT NULL,
   TIPO_AULA            VARCHAR(30)          NOT NULL,
   TIENE_PROYECTOR      SMALLINT             NOT NULL,
   DETALLE_EQUIPAMIENTO VARCHAR(500)         NULL,
   CONSTRAINT PK_AULA PRIMARY KEY NONCLUSTERED (ID_AULA),
   CONSTRAINT CHK_TIPO_AULA CHECK (TIPO_AULA IN ('AULA_NORMAL', 'LAB_COMPUTACION', 'LAB_FISICA', 'AUDITORIO')),
   CONSTRAINT CHK_TIENE_PROYECTOR CHECK (TIENE_PROYECTOR IN (0, 1))
)
go

/*==============================================================*/
/* Table: AUTORIA                                               */
/*==============================================================*/
CREATE TABLE AUTORIA (
   ID_PUBLICACION       INT                  NOT NULL,
   ID_DOCENTE           INT                  NOT NULL,
   ORDEN_AUTOR          INT                  NOT NULL,
   CONSTRAINT PK_AUTORIA PRIMARY KEY NONCLUSTERED (ID_PUBLICACION, ID_DOCENTE)
)
go

/*==============================================================*/
/* Index: ESCRIBE_ARTICULO_FK                                   */
/*==============================================================*/
CREATE INDEX ESCRIBE_ARTICULO_FK ON AUTORIA (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Index: TIENE_AUTORES_FK                                      */
/*==============================================================*/
CREATE INDEX TIENE_AUTORES_FK ON AUTORIA (
ID_PUBLICACION ASC
)
go

/*==============================================================*/
/* Table: CALIFICACION                                          */
/*==============================================================*/
CREATE TABLE CALIFICACION (
   ID_CALIFICACION      INT                  NOT NULL,
   ID_MATRICULA         INT                  NULL,
   ID_OFERTA            INT                  NULL,
   NOTA_PARCIAL_1       NUMERIC(4,2)         NOT NULL,
   NOTA_PARCIAL_2       NUMERIC(4,2)         NULL,
   NOTA_FINAL           NUMERIC(4,2)         NULL,
   NOTA_SUPLETORIO      NUMERIC(4,2)         NULL,
   NOTA_MEJORAMIENTO    NUMERIC(4,2)         NULL,
   ESTADO_APROBACION    VARCHAR(20)          NULL,
   ASISTENCIA_PORCENTAJE NUMERIC(5,2)         NOT NULL,
   CONSTRAINT PK_CALIFICACION PRIMARY KEY NONCLUSTERED (ID_CALIFICACION),
   CONSTRAINT CHK_NOTAS_RANGO CHECK ((NOTA_PARCIAL_1 BETWEEN 0 AND 10) AND
      (NOTA_PARCIAL_2 BETWEEN 0 AND 10 OR NOTA_PARCIAL_2 IS NULL) AND
      (NOTA_FINAL BETWEEN 0 AND 10 OR NOTA_FINAL IS NULL)),
   CONSTRAINT CHK_ASISTENCIA CHECK (ASISTENCIA_PORCENTAJE BETWEEN 0 AND 100)
)
go

/*==============================================================*/
/* Index: TIENE_DETALLE_NOTAS_FK                                */
/*==============================================================*/
CREATE INDEX TIENE_DETALLE_NOTAS_FK ON CALIFICACION (
ID_MATRICULA ASC
)
go

/*==============================================================*/
/* Index: GENERA_CALIFICACIONES_FK                              */
/*==============================================================*/
CREATE INDEX GENERA_CALIFICACIONES_FK ON CALIFICACION (
ID_OFERTA ASC
)
go

/*==============================================================*/
/* Table: CARRERA                                               */
/*==============================================================*/
CREATE TABLE CARRERA (
   ID_CARRERA           INT                  NOT NULL,
   ID_FACULTAD          INT                  NULL,
   ID_DOCENTE           INT                  NULL,
   NOMBRE_CARRERA       VARCHAR(100)         NOT NULL,
   NIVEL_CARRERA        VARCHAR(20)          NOT NULL,
   MODALIDAD_CARRERA    VARCHAR(20)          NOT NULL,
   DURACION_SEMESTRES   INT                  NOT NULL,
   CONSTRAINT PK_CARRERA PRIMARY KEY NONCLUSTERED (ID_CARRERA),
   CONSTRAINT CHK_NIVEL_CARRERA CHECK (NIVEL_CARRERA IN ('TECNICO', 'TECNOLOGICO', 'GRADO', 'POSGRADO')),
   CONSTRAINT CHK_MODALIDAD CHECK (MODALIDAD_CARRERA IN ('PRESENCIAL', 'SEMIPRESENCIAL', 'ONLINE'))
)
go

/*==============================================================*/
/* Index: ADMINISTRA_CARRERA_FK                                 */
/*==============================================================*/
CREATE INDEX ADMINISTRA_CARRERA_FK ON CARRERA (
ID_FACULTAD ASC
)
go

/*==============================================================*/
/* Index: TIENE_COORDINADOR2_FK                                 */
/*==============================================================*/
CREATE INDEX TIENE_COORDINADOR2_FK ON CARRERA (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Table: COLABORAN_EN                                          */
/*==============================================================*/
CREATE TABLE COLABORAN_EN (
   ID_PROYECTO          INT                  NOT NULL,
   ID_DOCENTE           INT                  NOT NULL,
   CONSTRAINT PK_COLABORAN_EN PRIMARY KEY NONCLUSTERED (ID_PROYECTO, ID_DOCENTE)
)
go

/*==============================================================*/
/* Index: COLABORAN_EN2_FK                                      */
/*==============================================================*/
CREATE INDEX COLABORAN_EN2_FK ON COLABORAN_EN (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Index: COLABORAN_EN_FK                                       */
/*==============================================================*/
CREATE INDEX COLABORAN_EN_FK ON COLABORAN_EN (
ID_PROYECTO ASC
)
go

/*==============================================================*/
/* Table: CORREQUISITO                                          */
/*==============================================================*/
CREATE TABLE CORREQUISITO (
   ASI_ID_ASIGNATURA    INT                  NOT NULL,
   ID_ASIGNATURA        INT                  NOT NULL,
   CONSTRAINT PK_CORREQUISITO PRIMARY KEY NONCLUSTERED (ASI_ID_ASIGNATURA, ID_ASIGNATURA)
)
go

/*==============================================================*/
/* Index: CORREQUISITO2_FK                                      */
/*==============================================================*/
CREATE INDEX CORREQUISITO2_FK ON CORREQUISITO (
ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Index: CORREQUISITO_FK                                       */
/*==============================================================*/
CREATE INDEX CORREQUISITO_FK ON CORREQUISITO (
ASI_ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
CREATE TABLE DEPARTAMENTO (
   ID_DEPARTAMENTO      INT                  NOT NULL,
   ID_FACULTAD          INT                  NULL,
   NOMBRE_DEPARTAMENTO  VARCHAR(100)         NOT NULL,
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY NONCLUSTERED (ID_DEPARTAMENTO)
)
go

/*==============================================================*/
/* Index: TIENE_DEPARTAMENTOS_FK                                */
/*==============================================================*/
CREATE INDEX TIENE_DEPARTAMENTOS_FK ON DEPARTAMENTO (
ID_FACULTAD ASC
)
go

/*==============================================================*/
/* Table: DETALLE_MALLA                                         */
/*==============================================================*/
CREATE TABLE DETALLE_MALLA (
   ID_ASIGNATURA        INT                  NOT NULL,
   ID_MALLA             INT                  NOT NULL,
   SEMESTRE_SUGERIDO    INT                  NOT NULL,
   HORAS_TEORICAS       INT                  NOT NULL,
   HORAS_PRACTICAS      INT                  NOT NULL,
   CONSTRAINT PK_DETALLE_MALLA PRIMARY KEY NONCLUSTERED (ID_ASIGNATURA, ID_MALLA)
)
go

/*==============================================================*/
/* Index: ES_PARTE_DE_MALLA_FK                                  */
/*==============================================================*/
CREATE INDEX ES_PARTE_DE_MALLA_FK ON DETALLE_MALLA (
ID_MALLA ASC
)
go

/*==============================================================*/
/* Index: SE_PRESENTA_EN_FK                                     */
/*==============================================================*/
CREATE INDEX SE_PRESENTA_EN_FK ON DETALLE_MALLA (
ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Table: DOCENTE                                               */
/*==============================================================*/
CREATE TABLE DOCENTE (
   ID_DOCENTE           INT                  NOT NULL,
   ID_FACULTAD          INT                  NULL,
   FAC_ID_FACULTAD      INT                  NULL,
   ID_CARRERA           INT                  NULL,
   NUMERO_UNICO         VARCHAR(9)           NOT NULL,
   CEDULA               VARCHAR(10)          NOT NULL,
   NOMBRES_DOCENTE      VARCHAR(100)         NOT NULL,
   APELLIDOS_DOCENTE    VARCHAR(100)         NOT NULL,
   EMAIL_INSTITUCIONAL  VARCHAR(100)         NOT NULL,
   TIPO_PROFESOR        VARCHAR(50)          NOT NULL,
   CATEGORIA_DOCENTE    VARCHAR(50)          NOT NULL,
   FECHA_INGRESO        DATETIME             NOT NULL,
   CONSTRAINT PK_DOCENTE PRIMARY KEY NONCLUSTERED (ID_DOCENTE),
   CONSTRAINT UQ_DOC_CEDULA UNIQUE (CEDULA),
   CONSTRAINT UQ_DOC_CODIGO UNIQUE (NUMERO_UNICO),
   CONSTRAINT UQ_DOC_EMAIL UNIQUE (EMAIL_INSTITUCIONAL)
)
go

/*==============================================================*/
/* Index: TIENE_DECANO_FK                                       */
/*==============================================================*/
CREATE INDEX TIENE_DECANO_FK ON DOCENTE (
ID_FACULTAD ASC
)
go

/*==============================================================*/
/* Index: ENSENIAN_EN_FK                                        */
/*==============================================================*/
CREATE INDEX ENSENIAN_EN_FK ON DOCENTE (
FAC_ID_FACULTAD ASC
)
go

/*==============================================================*/
/* Index: TIENE_COORDINADOR_FK                                  */
/*==============================================================*/
CREATE INDEX TIENE_COORDINADOR_FK ON DOCENTE (
ID_CARRERA ASC
)
go

/*==============================================================*/
/* Table: ESTUDIANTE                                            */
/*==============================================================*/
CREATE TABLE ESTUDIANTE (
   ID_ESTUDIANTE        INT                  NOT NULL,
   NUMERO_UNICO         VARCHAR(9)           NOT NULL,
   CEDULA               VARCHAR(10)          NOT NULL,
   NOMBRES_ESTUDIANTE   VARCHAR(100)         NOT NULL,
   APELLIDOS_ESTUDIANTE VARCHAR(100)         NOT NULL,
   EMAIL_INSTITUCIONAL  VARCHAR(100)         NOT NULL,
   FECHA_INGRESO        DATETIME             NOT NULL,
   ESTADO_ESTUDIANTE    VARCHAR(20)          NOT NULL,
   IRA                  NUMERIC(4,2)         NULL,
   CONSTRAINT PK_ESTUDIANTE PRIMARY KEY NONCLUSTERED (ID_ESTUDIANTE),
   CONSTRAINT UQ_EST_CEDULA UNIQUE (CEDULA),
   CONSTRAINT UQ_EST_MATRICULA UNIQUE (NUMERO_UNICO),
   CONSTRAINT UQ_EST_EMAIL UNIQUE (EMAIL_INSTITUCIONAL),
   CONSTRAINT CHK_ESTADO_ESTUDIANTE CHECK (ESTADO_ESTUDIANTE IN ('ACTIVO', 'INACTIVO', 'GRADUADO', 'RETIRADO', 'SUSPENDIDO'))
)
go

/*==============================================================*/
/* Table: FACULTAD                                              */
/*==============================================================*/
CREATE TABLE FACULTAD (
   ID_FACULTAD          INT                  NOT NULL,
   ID_DOCENTE           INT                  NULL,
   NOMBRE_FACULTAD      VARCHAR(100)         NOT NULL,
   NUMERO_EDIFICIO      INT                  NOT NULL,
   CONSTRAINT PK_FACULTAD PRIMARY KEY NONCLUSTERED (ID_FACULTAD)
)
go

/*==============================================================*/
/* Index: TIENE_DECANO2_FK                                      */
/*==============================================================*/
CREATE INDEX TIENE_DECANO2_FK ON FACULTAD (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Table: HISTORIAL_ACADEMICO                                   */
/*==============================================================*/
CREATE TABLE HISTORIAL_ACADEMICO (
   ID_HISTORIAL         INT                  NOT NULL,
   ID_ESTUDIANTE        INT                  NULL,
   ID_PERIODO           INT                  NULL,
   NOTA_DEFINITIVA      NUMERIC(4,2)         NOT NULL,
   ESTADO_MATERIA       VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_HISTORIAL_ACADEMICO PRIMARY KEY NONCLUSTERED (ID_HISTORIAL)
)
go

/*==============================================================*/
/* Index: TIENE_HISTORIALES_FK                                  */
/*==============================================================*/
CREATE INDEX TIENE_HISTORIALES_FK ON HISTORIAL_ACADEMICO (
ID_ESTUDIANTE ASC
)
go

/*==============================================================*/
/* Index: OBTUVO_RESULTADOS_EN_FK                               */
/*==============================================================*/
CREATE INDEX OBTUVO_RESULTADOS_EN_FK ON HISTORIAL_ACADEMICO (
ID_PERIODO ASC
)
go

/*==============================================================*/
/* Table: HORARIO_CLASE                                         */
/*==============================================================*/
CREATE TABLE HORARIO_CLASE (
   ID_HORARIO           INT                  NOT NULL,
   ID_AULA              INT                  NULL,
   ID_OFERTA            INT                  NULL,
   DIA_SEMANA           VARCHAR(15)          NOT NULL,
   HORA_INICIO          DATETIME             NOT NULL,
   HORA_FIN             DATETIME             NOT NULL,
   CONSTRAINT PK_HORARIO_CLASE PRIMARY KEY NONCLUSTERED (ID_HORARIO)
)
go

/*==============================================================*/
/* Index: TIENE_HORARIO_FK                                      */
/*==============================================================*/
CREATE INDEX TIENE_HORARIO_FK ON HORARIO_CLASE (
ID_AULA ASC
)
go

/*==============================================================*/
/* Index: SE_DICTA_EN_FK                                        */
/*==============================================================*/
CREATE INDEX SE_DICTA_EN_FK ON HORARIO_CLASE (
ID_OFERTA ASC
)
go

/*==============================================================*/
/* Table: LIBRO                                                 */
/*==============================================================*/
CREATE TABLE LIBRO (
   ID_LIBRO             INT                  NOT NULL,
   ISBN                 VARCHAR(20)          NOT NULL,
   TITULO_LIBRO         VARCHAR(200)         NOT NULL,
   AUTOR                VARCHAR(100)         NOT NULL,
   EDITORIAL            VARCHAR(100)         NOT NULL,
   STOCK_DISPONIBLE     INT                  NOT NULL,
   CONSTRAINT PK_LIBRO PRIMARY KEY NONCLUSTERED (ID_LIBRO),
   CONSTRAINT UQ_LIBRO_ISBN UNIQUE (ISBN)
)
go

/*==============================================================*/
/* Table: MALLA_CURRICULAR                                      */
/*==============================================================*/
CREATE TABLE MALLA_CURRICULAR (
   ID_MALLA             INT                  NOT NULL,
   ID_CARRERA           INT                  NULL,
   CODIGO_COHORTE       VARCHAR(10)          NOT NULL,
   FECHA_APROBACION     DATETIME             NOT NULL,
   TOTAL_CREDITOS       INT                  NOT NULL,
   ESTADO_MALLA         VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_MALLA_CURRICULAR PRIMARY KEY NONCLUSTERED (ID_MALLA)
)
go

/*==============================================================*/
/* Index: TIENE_CARRERA_FK                                      */
/*==============================================================*/
CREATE INDEX TIENE_CARRERA_FK ON MALLA_CURRICULAR (
ID_CARRERA ASC
)
go

/*==============================================================*/
/* Table: MATRICULA                                             */
/*==============================================================*/
CREATE TABLE MATRICULA (
   ID_MATRICULA         INT                  NOT NULL,
   ID_ESTUDIANTE        INT                  NULL,
   ID_PERIODO           INT                  NULL,
   FECHA_REGISTRO       DATETIME             NOT NULL,
   FORMA_MATRICULA      VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_MATRICULA PRIMARY KEY NONCLUSTERED (ID_MATRICULA)
)
go

/*==============================================================*/
/* Index: HA_REALIZADO_MATRICULA_FK                             */
/*==============================================================*/
CREATE INDEX HA_REALIZADO_MATRICULA_FK ON MATRICULA (
ID_ESTUDIANTE ASC
)
go

/*==============================================================*/
/* Index: SE_REALIZAN_PERIODO_FK                                */
/*==============================================================*/
CREATE INDEX SE_REALIZAN_PERIODO_FK ON MATRICULA (
ID_PERIODO ASC
)
go

/*==============================================================*/
/* Table: OFERTA_ASIGNATURA                                     */
/*==============================================================*/
CREATE TABLE OFERTA_ASIGNATURA (
   ID_OFERTA            INT                  NOT NULL,
   ID_PERIODO           INT                  NULL,
   ID_ASIGNATURA        INT                  NULL,
   ID_DOCENTE           INT                  NULL,
   CODIGO_PARALELO      VARCHAR(10)          NOT NULL,
   CUPO_MAXIMO          INT                  NOT NULL,
   CUPO_DISPONIBLE      INT                  NOT NULL,
   CONSTRAINT PK_OFERTA_ASIGNATURA PRIMARY KEY NONCLUSTERED (ID_OFERTA)
)
go

/*==============================================================*/
/* Index: TIENE_PERIODO_FK                                      */
/*==============================================================*/
CREATE INDEX TIENE_PERIODO_FK ON OFERTA_ASIGNATURA (
ID_PERIODO ASC
)
go

/*==============================================================*/
/* Index: TIENE_ASIGNATURA_FK                                   */
/*==============================================================*/
CREATE INDEX TIENE_ASIGNATURA_FK ON OFERTA_ASIGNATURA (
ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Index: DESIGNADO_OFERTA_FK                                   */
/*==============================================================*/
CREATE INDEX DESIGNADO_OFERTA_FK ON OFERTA_ASIGNATURA (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Table: PERIODO_ACADEMICO                                     */
/*==============================================================*/
CREATE TABLE PERIODO_ACADEMICO (
   ID_PERIODO           INT                  NOT NULL,
   CODIGO_PERIODO       VARCHAR(10)          NOT NULL,
   NOMBRE_PERIODO       VARCHAR(10)          NOT NULL,
   FECHA_INICIO         DATETIME             NOT NULL,
   FECHA_FIN            DATETIME             NOT NULL,
   ESTADO_PERIODO       VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_PERIODO_ACADEMICO PRIMARY KEY NONCLUSTERED (ID_PERIODO),
   CONSTRAINT UQ_PERIODO_CODIGO UNIQUE (CODIGO_PERIODO)
)
go

/*==============================================================*/
/* Table: PRESTAMO                                              */
/*==============================================================*/
CREATE TABLE PRESTAMO (
   FECHA_PRESTAMO       DATETIME             NOT NULL,
   ID_ESTUDIANTE        INT                  NULL,
   ID_LIBRO             INT                  NULL,
   FECHA_DEVOLUCION_PREVISTA DATETIME             NOT NULL,
   FECHA_DEVOLUCION_REAL DATETIME             NULL,
   CONSTRAINT PK_PRESTAMO PRIMARY KEY NONCLUSTERED (FECHA_PRESTAMO)
)
go

/*==============================================================*/
/* Index: SOLICITA_LIBRO_FK                                     */
/*==============================================================*/
CREATE INDEX SOLICITA_LIBRO_FK ON PRESTAMO (
ID_ESTUDIANTE ASC
)
go

/*==============================================================*/
/* Index: ES_PRESTADO_FK                                        */
/*==============================================================*/
CREATE INDEX ES_PRESTADO_FK ON PRESTAMO (
ID_LIBRO ASC
)
go

/*==============================================================*/
/* Table: PROCESO_TITULACION                                    */
/*==============================================================*/
CREATE TABLE PROCESO_TITULACION (
   ID_PROCESO           INT                  NOT NULL,
   ID_ESTUDIANTE        INT                  NULL,
   ID_DOCENTE           INT                  NULL,
   MODALIDAD_PROCESO    VARCHAR(30)          NOT NULL,
   TEMA_PROPUESTO       VARCHAR(300)         NOT NULL,
   FECHA_DEFENSA        DATETIME             NULL,
   NOTA_FINAL_GRADO     NUMERIC(4,2)         NULL,
   ESTADO_PROCESO       VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_PROCESO_TITULACION PRIMARY KEY NONCLUSTERED (ID_PROCESO),
   CONSTRAINT CHK_ESTADO_TITULACION CHECK (ESTADO_PROCESO IN ('ANTEPROYECTO', 'DESARROLLO', 'REVISION', 'CORRECCIONES', 'DEFENSA', 'APROBADO', 'RECHAZADO'))
)
go

/*==============================================================*/
/* Index: SOLICITA_TITULACION_FK                                */
/*==============================================================*/
CREATE INDEX SOLICITA_TITULACION_FK ON PROCESO_TITULACION (
ID_ESTUDIANTE ASC
)
go

/*==============================================================*/
/* Index: TUTORA_PROCESO_FK                                     */
/*==============================================================*/
CREATE INDEX TUTORA_PROCESO_FK ON PROCESO_TITULACION (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Table: PROYECTO_INVESTIGACION                                */
/*==============================================================*/
CREATE TABLE PROYECTO_INVESTIGACION (
   ID_PROYECTO          INT                  NOT NULL,
   ID_DOCENTE           INT                  NULL,
   ID_DEPARTAMENTO      INT                  NULL,
   CODIGO_PROYECTO      VARCHAR(20)          NOT NULL,
   TITULO_PROYECTO      VARCHAR(200)         NOT NULL,
   LINEA_INVESTIGACION  VARCHAR(100)         NOT NULL,
   PRESUPUESTO_ASIGNADO NUMERIC(10,2)        NOT NULL,
   FECHA_INICIO         DATETIME             NOT NULL,
   ESTADO_PROYECTO      VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_PROYECTO_INVESTIGACION PRIMARY KEY NONCLUSTERED (ID_PROYECTO)
)
go

/*==============================================================*/
/* Index: DIRIGE_PROYECTO_FK                                    */
/*==============================================================*/
CREATE INDEX DIRIGE_PROYECTO_FK ON PROYECTO_INVESTIGACION (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Index: GESTIONA_INVESTIGACION_FK                             */
/*==============================================================*/
CREATE INDEX GESTIONA_INVESTIGACION_FK ON PROYECTO_INVESTIGACION (
ID_DEPARTAMENTO ASC
)
go

/*==============================================================*/
/* Table: PUBLICACION                                           */
/*==============================================================*/
CREATE TABLE PUBLICACION (
   ID_PUBLICACION       INT                  NOT NULL,
   ID_PROYECTO          INT                  NULL,
   TITULO_PUBLICACION   VARCHAR(100)         NOT NULL,
   DOI                  VARCHAR(100)         NOT NULL,
   REVISTA              VARCHAR(100)         NOT NULL,
   CONSTRAINT PK_PUBLICACION PRIMARY KEY NONCLUSTERED (ID_PUBLICACION)
)
go

/*==============================================================*/
/* Index: PRODUCE_PUBLICACION_FK                                */
/*==============================================================*/
CREATE INDEX PRODUCE_PUBLICACION_FK ON PUBLICACION (
ID_PROYECTO ASC
)
go

/*==============================================================*/
/* Table: TIENE_PRERREQUISITO                                   */
/*==============================================================*/
CREATE TABLE TIENE_PRERREQUISITO (
   ASI_ID_ASIGNATURA    INT                  NOT NULL,
   ID_ASIGNATURA        INT                  NOT NULL,
   CONSTRAINT PK_TIENE_PRERREQUISITO PRIMARY KEY NONCLUSTERED (ASI_ID_ASIGNATURA, ID_ASIGNATURA)
)
go

/*==============================================================*/
/* Index: TIENE_PRERREQUISITO2_FK                               */
/*==============================================================*/
CREATE INDEX TIENE_PRERREQUISITO2_FK ON TIENE_PRERREQUISITO (
ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Index: TIENE_PRERREQUISITO_FK                                */
/*==============================================================*/
CREATE INDEX TIENE_PRERREQUISITO_FK ON TIENE_PRERREQUISITO (
ASI_ID_ASIGNATURA ASC
)
go

/*==============================================================*/
/* Table: TIPO_BECA                                             */
/*==============================================================*/
CREATE TABLE TIPO_BECA (
   ID_BECA              INT                  NOT NULL,
   NOMBRE_BECA          VARCHAR(100)         NOT NULL,
   CONSTRAINT PK_TIPO_BECA PRIMARY KEY NONCLUSTERED (ID_BECA)
)
go

/*==============================================================*/
/* Table: TITULO_ACADEMICO                                      */
/*==============================================================*/
CREATE TABLE TITULO_ACADEMICO (
   ID_TITULO            INT                  NOT NULL,
   ID_DOCENTE           INT                  NULL,
   NOMBRE_TITULO        VARCHAR(100)         NOT NULL,
   NIVEL_TITULO         VARCHAR(50)          NOT NULL,
   UNIVERSIDAD          VARCHAR(100)         NOT NULL,
   CONSTRAINT PK_TITULO_ACADEMICO PRIMARY KEY NONCLUSTERED (ID_TITULO)
)
go

/*==============================================================*/
/* Index: POSEE_TITULO_FK                                       */
/*==============================================================*/
CREATE INDEX POSEE_TITULO_FK ON TITULO_ACADEMICO (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Table: TRIBUNAL_GRADO                                        */
/*==============================================================*/
CREATE TABLE TRIBUNAL_GRADO (
   ID_PROCESO           INT                  NOT NULL,
   ID_DOCENTE           INT                  NOT NULL,
   CONSTRAINT PK_TRIBUNAL_GRADO PRIMARY KEY NONCLUSTERED (ID_PROCESO, ID_DOCENTE)
)
go

/*==============================================================*/
/* Index: TRIBUNAL_GRADO2_FK                                    */
/*==============================================================*/
CREATE INDEX TRIBUNAL_GRADO2_FK ON TRIBUNAL_GRADO (
ID_DOCENTE ASC
)
go

/*==============================================================*/
/* Index: TRIBUNAL_GRADO_FK                                     */
/*==============================================================*/
CREATE INDEX TRIBUNAL_GRADO_FK ON TRIBUNAL_GRADO (
ID_PROCESO ASC
)
go

ALTER TABLE ASIGNACION_BECA
   ADD CONSTRAINT FK_ASIGNACI_ES_TIPO_B_TIPO_BEC FOREIGN KEY (ID_BECA)
      REFERENCES TIPO_BECA (ID_BECA)
go

ALTER TABLE ASIGNACION_BECA
   ADD CONSTRAINT FK_ASIGNACI_RECIBE_BE_ESTUDIAN FOREIGN KEY (ID_ESTUDIANTE)
      REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
go

ALTER TABLE AUTORIA
   ADD CONSTRAINT FK_AUTORIA_ESCRIBE_A_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE AUTORIA
   ADD CONSTRAINT FK_AUTORIA_TIENE_AUT_PUBLICAC FOREIGN KEY (ID_PUBLICACION)
      REFERENCES PUBLICACION (ID_PUBLICACION)
go

ALTER TABLE CALIFICACION
   ADD CONSTRAINT FK_CALIFICA_GENERA_CA_OFERTA_A FOREIGN KEY (ID_OFERTA)
      REFERENCES OFERTA_ASIGNATURA (ID_OFERTA)
go

ALTER TABLE CALIFICACION
   ADD CONSTRAINT FK_CALIFICA_TIENE_DET_MATRICUL FOREIGN KEY (ID_MATRICULA)
      REFERENCES MATRICULA (ID_MATRICULA)
go

ALTER TABLE CARRERA
   ADD CONSTRAINT FK_CARRERA_ADMINISTR_FACULTAD FOREIGN KEY (ID_FACULTAD)
      REFERENCES FACULTAD (ID_FACULTAD)
go

ALTER TABLE CARRERA
   ADD CONSTRAINT FK_CARRERA_TIENE_COO_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE COLABORAN_EN
   ADD CONSTRAINT FK_COLABORA_COLABORAN_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE COLABORAN_EN
   ADD CONSTRAINT FK_COLABORA_COLABORAN_PROYECTO FOREIGN KEY (ID_PROYECTO)
      REFERENCES PROYECTO_INVESTIGACION (ID_PROYECTO)
go

ALTER TABLE CORREQUISITO
   ADD CONSTRAINT FK_CORREQ_ASIG_A FOREIGN KEY (ASI_ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE CORREQUISITO
   ADD CONSTRAINT FK_CORREQ_ASIG_B FOREIGN KEY (ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE DEPARTAMENTO
   ADD CONSTRAINT FK_DEPARTAM_TIENE_DEP_FACULTAD FOREIGN KEY (ID_FACULTAD)
      REFERENCES FACULTAD (ID_FACULTAD)
go

ALTER TABLE DETALLE_MALLA
   ADD CONSTRAINT FK_DETALLE__ES_PARTE__MALLA_CU FOREIGN KEY (ID_MALLA)
      REFERENCES MALLA_CURRICULAR (ID_MALLA)
go

ALTER TABLE DETALLE_MALLA
   ADD CONSTRAINT FK_DETALLE__SE_PRESEN_ASIGNATU FOREIGN KEY (ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE DOCENTE
   ADD CONSTRAINT FK_DOCENTE_ENSENIAN__FACULTAD FOREIGN KEY (FAC_ID_FACULTAD)
      REFERENCES FACULTAD (ID_FACULTAD)
go

ALTER TABLE DOCENTE
   ADD CONSTRAINT FK_DOCENTE_TIENE_COO_CARRERA FOREIGN KEY (ID_CARRERA)
      REFERENCES CARRERA (ID_CARRERA)
go

ALTER TABLE DOCENTE
   ADD CONSTRAINT FK_DOCENTE_TIENE_DEC_FACULTAD FOREIGN KEY (ID_FACULTAD)
      REFERENCES FACULTAD (ID_FACULTAD)
go

ALTER TABLE FACULTAD
   ADD CONSTRAINT FK_FACULTAD_TIENE_DEC_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE HISTORIAL_ACADEMICO
   ADD CONSTRAINT FK_HISTORIA_OBTUVO_RE_PERIODO_ FOREIGN KEY (ID_PERIODO)
      REFERENCES PERIODO_ACADEMICO (ID_PERIODO)
go

ALTER TABLE HISTORIAL_ACADEMICO
   ADD CONSTRAINT FK_HISTORIA_TIENE_HIS_ESTUDIAN FOREIGN KEY (ID_ESTUDIANTE)
      REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
go

ALTER TABLE HORARIO_CLASE
   ADD CONSTRAINT FK_HORARIO__SE_DICTA__OFERTA_A FOREIGN KEY (ID_OFERTA)
      REFERENCES OFERTA_ASIGNATURA (ID_OFERTA)
go

ALTER TABLE HORARIO_CLASE
   ADD CONSTRAINT FK_HORARIO__TIENE_HOR_AULA FOREIGN KEY (ID_AULA)
      REFERENCES AULA (ID_AULA)
go

ALTER TABLE MALLA_CURRICULAR
   ADD CONSTRAINT FK_MALLA_CU_TIENE_CAR_CARRERA FOREIGN KEY (ID_CARRERA)
      REFERENCES CARRERA (ID_CARRERA)
go

ALTER TABLE MATRICULA
   ADD CONSTRAINT FK_MATRICUL_HA_REALIZ_ESTUDIAN FOREIGN KEY (ID_ESTUDIANTE)
      REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
go

ALTER TABLE MATRICULA
   ADD CONSTRAINT FK_MATRICUL_SE_REALIZ_PERIODO_ FOREIGN KEY (ID_PERIODO)
      REFERENCES PERIODO_ACADEMICO (ID_PERIODO)
go

ALTER TABLE OFERTA_ASIGNATURA
   ADD CONSTRAINT FK_OFERTA_A_DESIGNADO_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE OFERTA_ASIGNATURA
   ADD CONSTRAINT FK_OFERTA_A_TIENE_ASI_ASIGNATU FOREIGN KEY (ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE OFERTA_ASIGNATURA
   ADD CONSTRAINT FK_OFERTA_A_TIENE_PER_PERIODO_ FOREIGN KEY (ID_PERIODO)
      REFERENCES PERIODO_ACADEMICO (ID_PERIODO)
go

ALTER TABLE PRESTAMO
   ADD CONSTRAINT FK_PRESTAMO_ES_PRESTA_LIBRO FOREIGN KEY (ID_LIBRO)
      REFERENCES LIBRO (ID_LIBRO)
go

ALTER TABLE PRESTAMO
   ADD CONSTRAINT FK_PRESTAMO_SOLICITA__ESTUDIAN FOREIGN KEY (ID_ESTUDIANTE)
      REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
go

ALTER TABLE PROCESO_TITULACION
   ADD CONSTRAINT FK_PROCESO__SOLICITA__ESTUDIAN FOREIGN KEY (ID_ESTUDIANTE)
      REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
go

ALTER TABLE PROCESO_TITULACION
   ADD CONSTRAINT FK_PROCESO__TUTORA_PR_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE PROYECTO_INVESTIGACION
   ADD CONSTRAINT FK_PROYECTO_DIRIGE_PR_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE PROYECTO_INVESTIGACION
   ADD CONSTRAINT FK_PROYECTO_GESTIONA__DEPARTAM FOREIGN KEY (ID_DEPARTAMENTO)
      REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
go

ALTER TABLE PUBLICACION
   ADD CONSTRAINT FK_PUBLICAC_PRODUCE_P_PROYECTO FOREIGN KEY (ID_PROYECTO)
      REFERENCES PROYECTO_INVESTIGACION (ID_PROYECTO)
go

ALTER TABLE TIENE_PRERREQUISITO
   ADD CONSTRAINT FK_PRERREQ_ASIG_HIJA FOREIGN KEY (ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE TIENE_PRERREQUISITO
   ADD CONSTRAINT FK_PRERREQ_ASIG_PADRE FOREIGN KEY (ASI_ID_ASIGNATURA)
      REFERENCES ASIGNATURA (ID_ASIGNATURA)
go

ALTER TABLE TITULO_ACADEMICO
   ADD CONSTRAINT FK_TITULO_A_POSEE_TIT_DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE TRIBUNAL_GRADO
   ADD CONSTRAINT FK_TRIBUNAL_TRIBUNAL__DOCENTE FOREIGN KEY (ID_DOCENTE)
      REFERENCES DOCENTE (ID_DOCENTE)
go

ALTER TABLE TRIBUNAL_GRADO
   ADD CONSTRAINT FK_TRIBUNAL_TRIBUNAL__PROCESO_ FOREIGN KEY (ID_PROCESO)
      REFERENCES PROCESO_TITULACION (ID_PROCESO)
go

