/* ==========================================================================
   FASE 2: ACADÉMICO Y CURRICULAR (POSTGRESQL - CORREGIDO V3)
   
   Correcciones:
   - Se agregaron LISTAS DE COLUMNAS EXPLÍCITAS en todos los INSERT para 
     evitar el error "invalid input syntax" por desajuste de orden de columnas.
   - Casting explícito ::DATE y ::TEXT mantenido.
   - Operadores de concatenación || mantenidos.
   ========================================================================== */

DO $$ BEGIN RAISE NOTICE '>>> INICIANDO FASE 2 (POSTGRESQL - CORREGIDO V3)...'; END $$;

/* ==========================================================================
   SECCIÓN 0: LIMPIEZA PREVIA
   ========================================================================== */
DO $$ BEGIN RAISE NOTICE '0. Limpiando datos previos de Fase 2...'; END $$;

DELETE FROM TIENE_PRERREQUISITO;
DELETE FROM CORREQUISITO;
DELETE FROM DETALLE_MALLA;
DELETE FROM MALLA_CURRICULAR;
DELETE FROM TITULO_ACADEMICO;
DELETE FROM ESTUDIANTE WHERE ID_ESTUDIANTE > 125;
DELETE FROM ASIGNATURA WHERE ID_ASIGNATURA > 50;
DELETE FROM CARRERA WHERE ID_CARRERA > 8;
DELETE FROM DOCENTE WHERE ID_DOCENTE > 25;

/* ==========================================================================
   SECCIÓN DE INSERCIÓN
   ========================================================================== */

-- 9. DOCENTES (75 registros)
DO $$ BEGIN RAISE NOTICE '9. Insertando resto de Docentes...'; END $$;

-- Se especifican columnas explícitamente para evitar error de orden
INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) 
VALUES (26, 1, 'DOC026', '1700000026', 'Marcelo', 'Ebrard', 'marcelo.ebrard@epn.edu.ec', 'TIEMPO_COMPLETO', 'AGREGADO', '2019-02-01');

INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) 
VALUES (27, 2, 'DOC027', '1700000027', 'Claudia', 'Shein', 'claudia.shein@epn.edu.ec', 'TIEMPO_COMPLETO', 'TITULAR', '2015-06-15');

INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) 
VALUES (28, 3, 'DOC028', '1700000028', 'Xochitl', 'Galvez', 'xochitl.galvez@epn.edu.ec', 'MEDIO_TIEMPO', 'AUXILIAR', '2021-03-10');

INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) 
VALUES (29, 4, 'DOC029', '1700000029', 'Samuel', 'Garcia', 'samuel.garcia@epn.edu.ec', 'TIEMPO_COMPLETO', 'AGREGADO', '2018-09-20');

INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO) 
VALUES (30, 5, 'DOC030', '1700000030', 'Luis', 'Colosio', 'luis.colosio@epn.edu.ec', 'TIEMPO_COMPLETO', 'TITULAR', '2010-01-01');

DO $$
DECLARE i INT;
BEGIN
    FOR i IN 31..100 LOOP
        INSERT INTO DOCENTE (ID_DOCENTE, ID_FACULTAD, NUMERO_UNICO, CEDULA, NOMBRES_DOCENTE, APELLIDOS_DOCENTE, EMAIL_INSTITUCIONAL, TIPO_PROFESOR, CATEGORIA_DOCENTE, FECHA_INGRESO)
        VALUES (
            i, (i % 8) + 1, 
            'DOC' || LPAD(i::text, 3, '0'),
            '1700000' || i::text,
            'DocenteNombre' || i::text, 'DocenteApellido' || i::text,
            'docente.' || i::text || '@epn.edu.ec',
            CASE WHEN i % 3 = 0 THEN 'MEDIO_TIEMPO' ELSE 'TIEMPO_COMPLETO' END,
            CASE WHEN i % 4 = 0 THEN 'AUXILIAR' WHEN i % 4 = 1 THEN 'AGREGADO' ELSE 'TITULAR' END,
            ('2023-01-01'::date - (i * 10))::date
        );
    END LOOP;
END $$;

-- 10. TÍTULOS ACADÉMICOS
DO $$ BEGIN RAISE NOTICE '10. Insertando Títulos...'; END $$;
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (1, 1, 'PhD en Ciencias de la Computación', 'DOCTORADO', 'MIT');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (2, 2, 'PhD en Administración de Empresas', 'DOCTORADO', 'Harvard');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (3, 3, 'PhD en Ingeniería Estructural', 'DOCTORADO', 'Stanford');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (4, 4, 'PhD en Sistemas Eléctricos', 'DOCTORADO', 'CalTech');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (5, 5, 'PhD en Termodinámica', 'DOCTORADO', 'TUM Germany');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (6, 6, 'PhD en Procesos Químicos', 'DOCTORADO', 'UNAM');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (7, 7, 'PhD en Matemáticas Puras', 'DOCTORADO', 'Oxford');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (8, 8, 'PhD en Geofísica', 'DOCTORADO', 'U. Tokyo');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (9, 9, 'MSc en Ingeniería de Software', 'MAESTRIA', 'EPN');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (10, 10, 'MBA', 'MAESTRIA', 'INCAE');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (11, 11, 'MSc en Hidráulica', 'MAESTRIA', 'UNAM');
INSERT INTO TITULO_ACADEMICO (ID_TITULO, ID_DOCENTE, NOMBRE_TITULO, NIVEL_TITULO, UNIVERSIDAD) VALUES (12, 12, 'MSc en Automatización', 'MAESTRIA', 'Politécnica Madrid');

-- 11. CARRERAS
DO $$ BEGIN RAISE NOTICE '11. Insertando Carreras...'; END $$;
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (9, 1, 26, 'Maestría en Ciberseguridad', 'POSGRADO', 'ONLINE', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (10, 1, 27, 'Maestría en Ciencia de Datos', 'POSGRADO', 'SEMIPRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (11, 2, 28, 'MBA Ejecutivo', 'POSGRADO', 'ONLINE', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (12, 3, 29, 'Maestría en Vías Terrestres', 'POSGRADO', 'PRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (13, 4, 30, 'Maestría en Energías Renovables', 'POSGRADO', 'SEMIPRESENCIAL', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (14, 5, 31, 'Maestría en Diseño Automotriz', 'POSGRADO', 'PRESENCIAL', 4);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (15, 6, 32, 'Maestría en Procesos Industriales', 'POSGRADO', 'PRESENCIAL', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (16, 7, 33, 'Doctorado en Matemática Aplicada', 'POSGRADO', 'PRESENCIAL', 8);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (17, 8, 34, 'Maestría en Hidrocarburos', 'POSGRADO', 'SEMIPRESENCIAL', 3);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (18, 1, 35, 'Tecnología en Desarrollo Web', 'TECNOLOGICO', 'ONLINE', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (19, 1, 36, 'Tecnología en Redes y Telecom', 'TECNOLOGICO', 'PRESENCIAL', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (20, 2, 37, 'Tecnología en Marketing Digital', 'TECNOLOGICO', 'ONLINE', 5);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (21, 3, 38, 'Ingeniería Ambiental', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (22, 4, 39, 'Ingeniería en Telecomunicaciones', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (23, 5, 40, 'Ingeniería Mecatrónica', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (24, 6, 41, 'Ingeniería en Alimentos', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (25, 7, 42, 'Física Nuclear', 'GRADO', 'PRESENCIAL', 10);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (26, 8, 43, 'Ingeniería Geológica', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (27, 2, 44, 'Economía', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (28, 1, 45, 'Ingeniería en Computación', 'GRADO', 'PRESENCIAL', 9);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (29, 3, 46, 'Arquitectura', 'GRADO', 'PRESENCIAL', 10);
INSERT INTO CARRERA (ID_CARRERA, ID_FACULTAD, ID_DOCENTE, NOMBRE_CARRERA, NIVEL_CARRERA, MODALIDAD_CARRERA, DURACION_SEMESTRES) VALUES (30, 4, 47, 'Ingeniería en Control', 'GRADO', 'PRESENCIAL', 9);

-- 12. ASIGNATURAS AVANZADAS
DO $$ BEGIN RAISE NOTICE '12. Insertando Asignaturas Avanzadas...'; END $$;
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (51, 'SW301', 'Inteligencia Artificial', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (52, 'SW302', 'Machine Learning', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (53, 'SW303', 'Deep Learning', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (54, 'SW304', 'Sistemas Operativos', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (55, 'SW305', 'Redes de Computadoras I', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (56, 'SW306', 'Redes de Computadoras II', 4, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (57, 'SW307', 'Seguridad Informática', 3, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (58, 'SW308', 'Desarrollo Web Fullstack', 4, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (59, 'SW309', 'Desarrollo Móvil', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (60, 'SW310', 'Cloud Computing', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (61, 'SW400', 'Tesis I', 5, 'OBLIGATORIA', 'Investigación');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (62, 'SW401', 'Tesis II', 5, 'OBLIGATORIA', 'Investigación');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (63, 'SW311', 'DevOps', 3, 'OPTATIVA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (64, 'SW312', 'QA y Testing', 3, 'OBLIGATORIA', 'Software');
INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO) VALUES (65, 'SW313', 'Arquitectura de Microservicios', 3, 'OPTATIVA', 'Software');

DO $$
DECLARE j INT;
BEGIN
    FOR j IN 66..200 LOOP
        INSERT INTO ASIGNATURA (ID_ASIGNATURA, CODIGO_ASIGNATURA, NOMBRE_ASIGNATURA, NUMERO_CREDITOS, TIPO_ASIGNATURA, AREA_CONOCIMIENTO)
        VALUES (
            j, 'GEN' || j::text,
            CASE WHEN j % 5 = 0 THEN 'Gestión de Proyectos ' || j::text
                 WHEN j % 5 = 1 THEN 'Matemática Avanzada ' || j::text
                 WHEN j % 5 = 2 THEN 'Física Aplicada ' || j::text
                 WHEN j % 5 = 3 THEN 'Administración ' || j::text
                 ELSE 'Tecnología Específica ' || j::text END,
            (j % 3) + 2,
            CASE WHEN j % 4 = 0 THEN 'OPTATIVA' ELSE 'OBLIGATORIA' END,
            'General'
        );
    END LOOP;
END $$;

/* --------------------------------------------------------------------------
   13. MALLAS CURRICULARES
   -------------------------------------------------------------------------- */
DO $$ BEGIN RAISE NOTICE '13. Creando Mallas Curriculares y Detalles...'; END $$;

-- Malla 1: Ingeniería de Software
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (1, 1, 'M-SOFT-22', '2022-01-15', 240, 'VIGENTE');
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (2, 2, 'M-ADM-22', '2022-01-20', 220, 'VIGENTE');
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (3, 3, 'M-CIV-21', '2021-06-15', 250, 'VIGENTE');
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (4, 4, 'M-ELE-20', '2020-09-01', 245, 'NO_VIGENTE');
INSERT INTO MALLA_CURRICULAR (ID_MALLA, ID_CARRERA, CODIGO_COHORTE, FECHA_APROBACION, TOTAL_CREDITOS, ESTADO_MALLA) VALUES (5, 4, 'M-ELE-24', '2024-01-10', 240, 'VIGENTE');

INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (1, 1, 1, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (2, 1, 1, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (10, 1, 1, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (11, 1, 1, 32, 64);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (3, 1, 2, 64, 32);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (21, 1, 2, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (22, 1, 3, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (23, 1, 3, 48, 48);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (24, 1, 4, 48, 16);
INSERT INTO DETALLE_MALLA (ID_ASIGNATURA, ID_MALLA, SEMESTRE_SUGERIDO, HORAS_TEORICAS, HORAS_PRACTICAS) VALUES (54, 1, 4, 48, 32);

/* --------------------------------------------------------------------------
   14. PRERREQUISITOS Y CORREQUISITOS
   -------------------------------------------------------------------------- */
DO $$ BEGIN RAISE NOTICE '14. Estableciendo Prerrequisitos y Correquisitos...'; END $$;

INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (1, 2);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (2, 3);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (3, 4);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (3, 5);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (10, 11);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (11, 21);
INSERT INTO TIENE_PRERREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (11, 22);
INSERT INTO CORREQUISITO (ASI_ID_ASIGNATURA, ID_ASIGNATURA) VALUES (6, 2);

/* --------------------------------------------------------------------------
   15. ESTUDIANTES LOTE 2 (125 Registros -> Total 250)
   -------------------------------------------------------------------------- */
DO $$ BEGIN RAISE NOTICE '15. Insertando Estudiantes Lote 2 (125 registros)...'; END $$;

DO $$
DECLARE k INT;
BEGIN
    FOR k IN 126..250 LOOP
        INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, NUMERO_UNICO, CEDULA, NOMBRES_ESTUDIANTE, APELLIDOS_ESTUDIANTE, EMAIL_INSTITUCIONAL, FECHA_INGRESO, ESTADO_ESTUDIANTE, IRA)
        VALUES (
            k,
            'EST' || k::text,
            '172000' || LPAD(k::text, 4, '0'),
            'Estudiante' || k::text,
            'Apellido' || k::text,
            'estudiante.' || k::text || '@epn.edu.ec',
            -- Casting explícito para evitar error de tipos
            CASE WHEN k % 2 = 0 THEN '2023-04-01'::DATE ELSE '2024-04-01'::DATE END,
            CASE WHEN k % 10 = 0 THEN 'SUSPENDIDO' ELSE 'ACTIVO' END,
            7.0 + (k % 30) / 10.0 
        );
    END LOOP;
END $$;

-- REINICIO DE SECUENCIAS
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM information_schema.sequences WHERE sequence_name = 'titulo_academico_id_titulo_seq') THEN
        PERFORM setval('titulo_academico_id_titulo_seq', (SELECT MAX(ID_TITULO) FROM TITULO_ACADEMICO));
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.sequences WHERE sequence_name = 'malla_curricular_id_malla_seq') THEN
        PERFORM setval('malla_curricular_id_malla_seq', (SELECT MAX(ID_MALLA) FROM MALLA_CURRICULAR));
    END IF;
    RAISE NOTICE '>>> FASE 2 COMPLETADA CON ÉXITO.';
END $$;